[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hpms"
authors = [
    { name = "sagarmemane135", email = "wjones13522@gmail.com" }
]
description = "Hospital & Patient Management System for Frappe v16"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[project.urls]
Homepage = "https://github.com/sagarmemane135/Frappe-Prod-Ready-Setup"

[tool.flit.module]
name = "hpms"
